templates:
  frontend:
    version: "v1.0.0"
    description: "React/Vue.js frontend template with TypeScript"
    path: "templates/frontend"
    
  backend:
    version: "v1.0.0"
    description: "Node.js/Express backend template with TypeScript"
    path: "templates/backend"
    
  mobile:
    version: "v1.0.0"
    description: "React Native mobile app template"
    path: "templates/mobile"
    
  fullstack:
    version: "v1.0.0"
    description: "Full-stack application template"
    path: "templates/fullstack"

cli:
  version: "1.0.0"
  min_version: "1.0.0"